<div class="txt promo">
        <div class="sliding-text-promo p-1 bg-light-inv">GET 10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | GET 10%-OFF
            VOUCHER FOR YOUR
            FIRST TIME ORDER | GET 10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | GET 10%-OFF VOUCHER FOR YOUR FIRST TIME
            ORDER | GET 10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | GET 10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | GET
            10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | GET 10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | GET 10%-OFF
            VOUCHER FOR YOUR FIRST TIME ORDER | GET 10%-OFF VOUCHER FOR YOUR FIRST TIME ORDER | </div>
</div>