name: Update Badge

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          visits=$(curl -s https://api.countapi.xyz/hit/sceiiya/animazooki/readme-visits)
          sed -i "s/Visits-[0-9]*/Visits-$visits/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git commit -am "Update visits badge"
          git push
